// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: proto/document.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LiveDocument_SyncDocument_FullMethodName = "/LiveDocument/SyncDocument"
)

// LiveDocumentClient is the client API for LiveDocument service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LiveDocumentClient interface {
	SyncDocument(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DocumentChange, DocumentChange], error)
}

type liveDocumentClient struct {
	cc grpc.ClientConnInterface
}

func NewLiveDocumentClient(cc grpc.ClientConnInterface) LiveDocumentClient {
	return &liveDocumentClient{cc}
}

func (c *liveDocumentClient) SyncDocument(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DocumentChange, DocumentChange], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LiveDocument_ServiceDesc.Streams[0], LiveDocument_SyncDocument_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DocumentChange, DocumentChange]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LiveDocument_SyncDocumentClient = grpc.BidiStreamingClient[DocumentChange, DocumentChange]

// LiveDocumentServer is the server API for LiveDocument service.
// All implementations must embed UnimplementedLiveDocumentServer
// for forward compatibility.
type LiveDocumentServer interface {
	SyncDocument(grpc.BidiStreamingServer[DocumentChange, DocumentChange]) error
	mustEmbedUnimplementedLiveDocumentServer()
}

// UnimplementedLiveDocumentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLiveDocumentServer struct{}

func (UnimplementedLiveDocumentServer) SyncDocument(grpc.BidiStreamingServer[DocumentChange, DocumentChange]) error {
	return status.Errorf(codes.Unimplemented, "method SyncDocument not implemented")
}
func (UnimplementedLiveDocumentServer) mustEmbedUnimplementedLiveDocumentServer() {}
func (UnimplementedLiveDocumentServer) testEmbeddedByValue()                      {}

// UnsafeLiveDocumentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LiveDocumentServer will
// result in compilation errors.
type UnsafeLiveDocumentServer interface {
	mustEmbedUnimplementedLiveDocumentServer()
}

func RegisterLiveDocumentServer(s grpc.ServiceRegistrar, srv LiveDocumentServer) {
	// If the following call pancis, it indicates UnimplementedLiveDocumentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LiveDocument_ServiceDesc, srv)
}

func _LiveDocument_SyncDocument_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LiveDocumentServer).SyncDocument(&grpc.GenericServerStream[DocumentChange, DocumentChange]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LiveDocument_SyncDocumentServer = grpc.BidiStreamingServer[DocumentChange, DocumentChange]

// LiveDocument_ServiceDesc is the grpc.ServiceDesc for LiveDocument service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LiveDocument_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "LiveDocument",
	HandlerType: (*LiveDocumentServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SyncDocument",
			Handler:       _LiveDocument_SyncDocument_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/document.proto",
}
