# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='schema.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0cschema.proto\"\n\n\x08\x45mptyreq\"6\n\x15GetLabyrinthInfoReply\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\"w\n\x14GetPlayerStatusReply\x12\x14\n\x0cplayer_score\x18\x01 \x01(\x05\x12\x15\n\rplayer_health\x18\x02 \x01(\x05\x12\x10\n\x08player_x\x18\x03 \x01(\x05\x12\x10\n\x08player_y\x18\x04 \x01(\x05\x12\x0e\n\x06spells\x18\x05 \x01(\x05\"(\n\x13RegisterMoveRequest\x12\x11\n\tdirection\x18\x01 \x01(\t\"#\n\x11RegisterMoveReply\x12\x0e\n\x06status\x18\x01 \x01(\t\"8\n\x0eRevelioRequest\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\x10\n\x08tiletype\x18\x03 \x01(\t\"6\n\x0cRevelioReply\x12\x12\n\nrevealed_x\x18\x01 \x03(\x05\x12\x12\n\nrevealed_y\x18\x02 \x03(\x05\"\'\n\x0f\x42ombardaRequest\x12\t\n\x01x\x18\x01 \x03(\x05\x12\t\n\x01y\x18\x02 \x03(\x05\"\x1f\n\rBombardaReply\x12\x0e\n\x06status\x18\x01 \x01(\t2\xc3\x02\n\x0c\x41ll_Services\x12*\n\x07initrpc\x12\t.Emptyreq\x1a\x12.RegisterMoveReply\"\x00\x12\x37\n\x10GetLabyrinthInfo\x12\t.Emptyreq\x1a\x16.GetLabyrinthInfoReply\"\x00\x12\x35\n\x0fGetPlayerStatus\x12\t.Emptyreq\x1a\x15.GetPlayerStatusReply\"\x00\x12:\n\x0cRegisterMove\x12\x14.RegisterMoveRequest\x1a\x12.RegisterMoveReply\"\x00\x12+\n\x07Revelio\x12\x0f.RevelioRequest\x1a\r.RevelioReply\"\x00\x12.\n\x08\x42ombarda\x12\x10.BombardaRequest\x1a\x0e.BombardaReply\"\x00\x62\x06proto3')
)




_EMPTYREQ = _descriptor.Descriptor(
  name='Emptyreq',
  full_name='Emptyreq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=26,
)


_GETLABYRINTHINFOREPLY = _descriptor.Descriptor(
  name='GetLabyrinthInfoReply',
  full_name='GetLabyrinthInfoReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='GetLabyrinthInfoReply.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='GetLabyrinthInfoReply.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=82,
)


_GETPLAYERSTATUSREPLY = _descriptor.Descriptor(
  name='GetPlayerStatusReply',
  full_name='GetPlayerStatusReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='player_score', full_name='GetPlayerStatusReply.player_score', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player_health', full_name='GetPlayerStatusReply.player_health', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player_x', full_name='GetPlayerStatusReply.player_x', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player_y', full_name='GetPlayerStatusReply.player_y', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='spells', full_name='GetPlayerStatusReply.spells', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=203,
)


_REGISTERMOVEREQUEST = _descriptor.Descriptor(
  name='RegisterMoveRequest',
  full_name='RegisterMoveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='direction', full_name='RegisterMoveRequest.direction', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=245,
)


_REGISTERMOVEREPLY = _descriptor.Descriptor(
  name='RegisterMoveReply',
  full_name='RegisterMoveReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='RegisterMoveReply.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=247,
  serialized_end=282,
)


_REVELIOREQUEST = _descriptor.Descriptor(
  name='RevelioRequest',
  full_name='RevelioRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='RevelioRequest.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='RevelioRequest.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tiletype', full_name='RevelioRequest.tiletype', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=284,
  serialized_end=340,
)


_REVELIOREPLY = _descriptor.Descriptor(
  name='RevelioReply',
  full_name='RevelioReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='revealed_x', full_name='RevelioReply.revealed_x', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='revealed_y', full_name='RevelioReply.revealed_y', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=342,
  serialized_end=396,
)


_BOMBARDAREQUEST = _descriptor.Descriptor(
  name='BombardaRequest',
  full_name='BombardaRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='BombardaRequest.x', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='BombardaRequest.y', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=398,
  serialized_end=437,
)


_BOMBARDAREPLY = _descriptor.Descriptor(
  name='BombardaReply',
  full_name='BombardaReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='BombardaReply.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=439,
  serialized_end=470,
)

DESCRIPTOR.message_types_by_name['Emptyreq'] = _EMPTYREQ
DESCRIPTOR.message_types_by_name['GetLabyrinthInfoReply'] = _GETLABYRINTHINFOREPLY
DESCRIPTOR.message_types_by_name['GetPlayerStatusReply'] = _GETPLAYERSTATUSREPLY
DESCRIPTOR.message_types_by_name['RegisterMoveRequest'] = _REGISTERMOVEREQUEST
DESCRIPTOR.message_types_by_name['RegisterMoveReply'] = _REGISTERMOVEREPLY
DESCRIPTOR.message_types_by_name['RevelioRequest'] = _REVELIOREQUEST
DESCRIPTOR.message_types_by_name['RevelioReply'] = _REVELIOREPLY
DESCRIPTOR.message_types_by_name['BombardaRequest'] = _BOMBARDAREQUEST
DESCRIPTOR.message_types_by_name['BombardaReply'] = _BOMBARDAREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Emptyreq = _reflection.GeneratedProtocolMessageType('Emptyreq', (_message.Message,), dict(
  DESCRIPTOR = _EMPTYREQ,
  __module__ = 'schema_pb2'
  # @@protoc_insertion_point(class_scope:Emptyreq)
  ))
_sym_db.RegisterMessage(Emptyreq)

GetLabyrinthInfoReply = _reflection.GeneratedProtocolMessageType('GetLabyrinthInfoReply', (_message.Message,), dict(
  DESCRIPTOR = _GETLABYRINTHINFOREPLY,
  __module__ = 'schema_pb2'
  # @@protoc_insertion_point(class_scope:GetLabyrinthInfoReply)
  ))
_sym_db.RegisterMessage(GetLabyrinthInfoReply)

GetPlayerStatusReply = _reflection.GeneratedProtocolMessageType('GetPlayerStatusReply', (_message.Message,), dict(
  DESCRIPTOR = _GETPLAYERSTATUSREPLY,
  __module__ = 'schema_pb2'
  # @@protoc_insertion_point(class_scope:GetPlayerStatusReply)
  ))
_sym_db.RegisterMessage(GetPlayerStatusReply)

RegisterMoveRequest = _reflection.GeneratedProtocolMessageType('RegisterMoveRequest', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERMOVEREQUEST,
  __module__ = 'schema_pb2'
  # @@protoc_insertion_point(class_scope:RegisterMoveRequest)
  ))
_sym_db.RegisterMessage(RegisterMoveRequest)

RegisterMoveReply = _reflection.GeneratedProtocolMessageType('RegisterMoveReply', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERMOVEREPLY,
  __module__ = 'schema_pb2'
  # @@protoc_insertion_point(class_scope:RegisterMoveReply)
  ))
_sym_db.RegisterMessage(RegisterMoveReply)

RevelioRequest = _reflection.GeneratedProtocolMessageType('RevelioRequest', (_message.Message,), dict(
  DESCRIPTOR = _REVELIOREQUEST,
  __module__ = 'schema_pb2'
  # @@protoc_insertion_point(class_scope:RevelioRequest)
  ))
_sym_db.RegisterMessage(RevelioRequest)

RevelioReply = _reflection.GeneratedProtocolMessageType('RevelioReply', (_message.Message,), dict(
  DESCRIPTOR = _REVELIOREPLY,
  __module__ = 'schema_pb2'
  # @@protoc_insertion_point(class_scope:RevelioReply)
  ))
_sym_db.RegisterMessage(RevelioReply)

BombardaRequest = _reflection.GeneratedProtocolMessageType('BombardaRequest', (_message.Message,), dict(
  DESCRIPTOR = _BOMBARDAREQUEST,
  __module__ = 'schema_pb2'
  # @@protoc_insertion_point(class_scope:BombardaRequest)
  ))
_sym_db.RegisterMessage(BombardaRequest)

BombardaReply = _reflection.GeneratedProtocolMessageType('BombardaReply', (_message.Message,), dict(
  DESCRIPTOR = _BOMBARDAREPLY,
  __module__ = 'schema_pb2'
  # @@protoc_insertion_point(class_scope:BombardaReply)
  ))
_sym_db.RegisterMessage(BombardaReply)



_ALL_SERVICES = _descriptor.ServiceDescriptor(
  name='All_Services',
  full_name='All_Services',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=473,
  serialized_end=796,
  methods=[
  _descriptor.MethodDescriptor(
    name='initrpc',
    full_name='All_Services.initrpc',
    index=0,
    containing_service=None,
    input_type=_EMPTYREQ,
    output_type=_REGISTERMOVEREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetLabyrinthInfo',
    full_name='All_Services.GetLabyrinthInfo',
    index=1,
    containing_service=None,
    input_type=_EMPTYREQ,
    output_type=_GETLABYRINTHINFOREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetPlayerStatus',
    full_name='All_Services.GetPlayerStatus',
    index=2,
    containing_service=None,
    input_type=_EMPTYREQ,
    output_type=_GETPLAYERSTATUSREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RegisterMove',
    full_name='All_Services.RegisterMove',
    index=3,
    containing_service=None,
    input_type=_REGISTERMOVEREQUEST,
    output_type=_REGISTERMOVEREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Revelio',
    full_name='All_Services.Revelio',
    index=4,
    containing_service=None,
    input_type=_REVELIOREQUEST,
    output_type=_REVELIOREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Bombarda',
    full_name='All_Services.Bombarda',
    index=5,
    containing_service=None,
    input_type=_BOMBARDAREQUEST,
    output_type=_BOMBARDAREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ALL_SERVICES)

DESCRIPTOR.services_by_name['All_Services'] = _ALL_SERVICES

# @@protoc_insertion_point(module_scope)
