# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import schema_pb2 as schema__pb2


class All_ServicesStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.initrpc = channel.unary_unary(
        '/All_Services/initrpc',
        request_serializer=schema__pb2.Emptyreq.SerializeToString,
        response_deserializer=schema__pb2.RegisterMoveReply.FromString,
        )
    self.GetLabyrinthInfo = channel.unary_unary(
        '/All_Services/GetLabyrinthInfo',
        request_serializer=schema__pb2.Emptyreq.SerializeToString,
        response_deserializer=schema__pb2.GetLabyrinthInfoReply.FromString,
        )
    self.GetPlayerStatus = channel.unary_unary(
        '/All_Services/GetPlayerStatus',
        request_serializer=schema__pb2.Emptyreq.SerializeToString,
        response_deserializer=schema__pb2.GetPlayerStatusReply.FromString,
        )
    self.RegisterMove = channel.unary_unary(
        '/All_Services/RegisterMove',
        request_serializer=schema__pb2.RegisterMoveRequest.SerializeToString,
        response_deserializer=schema__pb2.RegisterMoveReply.FromString,
        )
    self.Revelio = channel.unary_unary(
        '/All_Services/Revelio',
        request_serializer=schema__pb2.RevelioRequest.SerializeToString,
        response_deserializer=schema__pb2.RevelioReply.FromString,
        )
    self.Bombarda = channel.unary_unary(
        '/All_Services/Bombarda',
        request_serializer=schema__pb2.BombardaRequest.SerializeToString,
        response_deserializer=schema__pb2.BombardaReply.FromString,
        )


class All_ServicesServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def initrpc(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetLabyrinthInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPlayerStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RegisterMove(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Revelio(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Bombarda(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_All_ServicesServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'initrpc': grpc.unary_unary_rpc_method_handler(
          servicer.initrpc,
          request_deserializer=schema__pb2.Emptyreq.FromString,
          response_serializer=schema__pb2.RegisterMoveReply.SerializeToString,
      ),
      'GetLabyrinthInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetLabyrinthInfo,
          request_deserializer=schema__pb2.Emptyreq.FromString,
          response_serializer=schema__pb2.GetLabyrinthInfoReply.SerializeToString,
      ),
      'GetPlayerStatus': grpc.unary_unary_rpc_method_handler(
          servicer.GetPlayerStatus,
          request_deserializer=schema__pb2.Emptyreq.FromString,
          response_serializer=schema__pb2.GetPlayerStatusReply.SerializeToString,
      ),
      'RegisterMove': grpc.unary_unary_rpc_method_handler(
          servicer.RegisterMove,
          request_deserializer=schema__pb2.RegisterMoveRequest.FromString,
          response_serializer=schema__pb2.RegisterMoveReply.SerializeToString,
      ),
      'Revelio': grpc.unary_unary_rpc_method_handler(
          servicer.Revelio,
          request_deserializer=schema__pb2.RevelioRequest.FromString,
          response_serializer=schema__pb2.RevelioReply.SerializeToString,
      ),
      'Bombarda': grpc.unary_unary_rpc_method_handler(
          servicer.Bombarda,
          request_deserializer=schema__pb2.BombardaRequest.FromString,
          response_serializer=schema__pb2.BombardaReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'All_Services', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
